# Install Docker and run image in VMs
- name: Install docker
  hosts: all
  become: yes
  gather_facts: False
  tasks:
  - name: Update apt
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Add docker GPG key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present
  - name: Add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Install docker
    apt:
      name: ['docker-ce','docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
      state: present
      update_cache: yes
  - name: Install docker deps
    apt:
      name: ['python3-pip','python3-setuptools','virtualenv']
  - name: Install docker SDK
    pip:
      name: docker-compose
- name: Pull & Run image
  hosts: all
  become: yes
  gather_facts: False
  tasks:
  - name: Pull image
    community.docker.docker_image:
      name: stevenspinoza/kub-first-app
      source: pull
  - name: Run container
    community.docker.docker_container:
      name: kfa
      image: stevenspinoza/kub-first-app:argo91
      state: started
      #network_mode: host => exposes docker exposed port
      network_mode: host
        
  
