---
- name: Deploy app in AKS namespace
  hosts: localhost
  tasks:
  - name: Create AKS namespace
    k8s:
      name: my-app
      api_version: v1
      kind: Namespace
      state: present
      kubeconfig: aks-dev-kubeconfig
  - name: Deploy app
    k8s:
      src: kub-deploy/master.yml
      state: present
      kubeconfig: aks-dev-kubeconfig
      namespace: my-app
