---
- name: Install python3, docker, docker-compose
  hosts: all
  become: yes
  gather_facts: False
  roles:
    - install_docker_azure_vm
    

- name: Create new linux user
  hosts: all
  become: yes
  roles:
    - create_user


- name: Start docker containers
  hosts: all
  become: yes
  become_user: nana
  vars:
    allow_world_readable_tmpfiles: true
  vars_files:
    - project-vars
  roles:
    - start_containers
    