- name: Copy docker compose
  copy:
    src: /home/ss/ansible/docker-compose.yaml
    dest: /home/nana/docker-compose.yaml

# - name: Docker login
#   docker_login: 
#     registry_url: https://index.docker.io/v1/
#     username: stevenspinoza
#     password: "{{docker_password}}"

- name: Start container from compose
  docker_compose: 
    project_src: /home/nana